media:
  - name: projects-images
    label: Media des projets
    input: public/content/projects
    output: /content/projects

content:
  - name: projects
    label: Projets
    type: collection
    path: src/data/content/projects
    format: json-frontmatter
    fields:
      - name: cover
        label: Image illustrative
        required: true
        type: image
        options:
          path: covers
      - name: title
        label: Nom
        required: true
      - name: description
        label: Résumé
        required: true
      - name: tags
        label: Tags (l'ordre importe)
        required: false
        list: true
        type: string
        options:
          minlength: 3
          maxlength: 20

      - name: poster
        label: Image grand-format
        required: false
        type: image
        options:
          path: posters
      - name: body
        label: Présentation
        type: rich-text
