name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-slim
    steps:
      - name: Trigger deploy hook
        run: |
          if curl -X POST -d {} ${{ secrets.NETLIFY_DEPLOY_HOOK }};
          then
            echo "::notice::Website has been deployed."
          else
            echo "::error::Failed to deploy website."
          fi
