# -------------------------------------------------
# | Trigger a deploy from current state of the    |
# | 'main' branch.                                |
# |                                               |
# | This is useful because I can trigger deploy   |
# | only when I finished edition on PagesCMS      |
# -------------------------------------------------

name: Deploy & publish main

on:
  workflow_dispatch:
    inputs:
      payload:
        description: Pages CMS payload
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-slim
    steps:
      - name: Debug PagesCMS Payload
        if: inputs.payload
        run: |
          echo "::notice::Deploy triggered via PagesCMS"
          echo '${{ inputs.payload }}' | jq .

      - name: Install required tools
        run: |
          # Installing bun
          curl -fsSL https://bun.com/install | bash
          # Registering bun
          source ~/.bash_profile

          # Installing netlify cli
          bun a -g netlify-cli

      - name: Retreive content
        uses: actions/checkout@v6
        with:
          # We hard-code 'main' because this is the production deploy
          ref: main

      - name: Deploy website
        run: |
          NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify deploy
