# -------------------------------------------------
# | Merge a branch into another without touching  |
# | the "into" branch's content.                  |
# |                                               |
# | This is useful because GitHub does not        |
# | the "ours" merge strategy.                    |
# -------------------------------------------------

name: Structure merger

on:
  # When pushing to dev AND package.json's version are different
  push:
    branches:
      - dev

  workflow_dispatch:
    inputs:
      verify-version:
        default: false
        type: boolean
        required: true
        description: If you want to abort the merge if the package.json's version are the same in both branches

      from:
        default: dev
        type: string
        required: true
        description: The name of the branch to copy the structure from
      to:
        default: main
        type: string
        required: true
        description: The name of the branch to copy the structure to

env:
  FROM: ${{ inputs.from || 'dev' }}
  TO: ${{ inputs.to || 'merge-test' }}
  CHECK_VERSION: ${{ inputs.verify-version == null || inputs.verify-version }}
  IGNORED_DIRECTORIES: (public/content src/data/content)

jobs:
  ensure-mergable:
    runs-on: ubuntu-slim
    outputs:
      target_exists: ${{ steps.target.outputs.exists }}
    steps:
      - uses: actions/checkout@v6
      - name: Ensure ${{ env.FROM }} branch exists
        run: |
          FROM_EXISTS=$(git branch --list '${{env.FROM}}')
          if [ -z "$FROM_EXISTS" ]; 
          then
            echo "::error::The branch ${{env.FROM}} does not exist."
            exit 1
          fi
      - name: Check if branch ${{ env.TO }}
        id: target
        run: |
          TO_EXISTS=$(git branch --list '${{env.TO}}')
          RESULT=1

          if [ -z "$TO_EXISTS" ]; 
          then
            echo "::notice::The branch ${{env.TO}} does not exist."
            RESULT=0
          fi

          echo "exists=$RESULT" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v6
        if: steps.target.outputs.exists == 1
        with:
          ref: ${{ env.TO }}
      - name: Check mergability
        if: steps.target.outputs.exists == 1
        run: |
          git merge --no-ff --no-commit ${{ env.FROM }}
          CONFLICTING=$(git diff --name-only --diff-filter=U --relative)
          if [ ! "$CONFLICTING" = "" ]; 
          then
            echo "::error::Somes files are conflicting between branches ${{ env.FROM }} and ${{ env.TO }}."
            exit 1;
          fi

  check-version:
    runs-on: ubuntu-slim
    needs:
      - ensure-mergable
    if: github.env.CHECK_VERSION && needs.ensure-mergable.outputs.target_exists
    outputs:
      same: ${{ steps.matcher.outputs.same }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.TO }}
      - name: Fetch current version
        if: env.CHECK_VERSION
        run: EXISTING_VERSION=$(grep "version" ./package.json | grep -oP "\d.+(?=\")")
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.FROM }}
      - name: Fetch mergin version
        run: MERGING_VERSION=$(grep "version" ./package.json | grep -oP "\d.+(?=\")")
      - name: Verify versions
        id: matcher
        run: |
          SAME=0

          if [ "$EXISTING_VERSION" = "$MERGIN_VERSION" ]; 
          then
            echo "::notice::Both versions matches. The merge will not append."
            SAME=1
          else
            echo "::notice::Versions differ. Passing from '$EXISTING_VERSION' to '$MERGING_VERSION'."
          fi

          echo "same=$SAME" >> $GITHUB_OUTPUT

  merge:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs:
      - check-version
      - ensure-mergable
    if: always() && ! ( needs.ensure-mergable.outputs.target_exists && needs.check-version.outputs.same )
    env:
      TMP_BRANCH: tmp/content-skipper
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.FROM }}
      - name: Switch to the ${{ env.TMP_BRANCH }} tempory branch
        run: git switch -c ${{ env.TMP_BRANCH }}

      - name: Create the .gitignore files
        env:
          TARGET_EXISTS: ${{ needs.ensure-mergable.outputs.target_exists }}
        run: |
          for DIR in ${IGNORED_DIRECTORIES[@]}; do
            DIR="./$DIR"

            if [ -d $DIR ]; then
              if [ "$TARGET_EXISTS" = "1"]; then
                git checkout ${{ env.FROM }} $DIR
              else
                rm -rf $DIR
              fi
            fi
          done

      - name: Saving changes
        uses: EndBug/add-and-commit@v10
        with:
          message: "workflow: Excluding content files"

      - name: Merge from ${{ env.TMP_BRANCH }} to ${{ env.TO }}
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ env.TO }}
          force: true
